import { SkillFile } from './types';

export const LOBSTER_WORKFLOW_SKILL_CONTENT = [
  '---',
  'name: lobster-project-workflow',
  'description: Use when working in the 知栈 Agent and Skill management platform repository',
  '---',
  '',
  '# 知栈 Project Workflow',
  '',
  'Use this skill for 知栈 frontend, backend, Skill Package, Agent sync, memory, goal, token, config event, and release work.',
  '',
  '## Start Here',
  '1. Identify the task type below.',
  '2. Read only the matching workflow first.',
  '3. Read referenced files only when the workflow calls for them.',
  '',
  '## Workflows',
  '| Task | Read |',
  '|---|---|',
  '| Change frontend or backend code | `workflows/project-change.md` |',
  '| Create or update a Skill Package | `workflows/skill-package-upload.md` |',
  '| Sync skills, memories, or goals from an Agent | `workflows/agent-sync-preview.md` |',
  '| Poll platform config changes and ack them | `workflows/config-event-listening.md` |',
  '| Prepare a release or final report | `workflows/release-verification.md` |',
  '',
  '## References',
  '| Need | Read |',
  '|---|---|',
  '| Domain rules and source-of-truth tables | `references/domain-rules.md` |',
  '| AI-facing endpoints and payload fields | `references/api-endpoints.md` |',
  '| Failure diagnosis | `references/troubleshooting.md` |',
  '| Short execution checklist | `checklists/lobster-checklist.md` |',
  '',
  '## Safety Boundaries',
  '- Do not write Agent Tokens, secrets, private user data, deployment passwords, or raw credentials into Skill files, memories, goals, docs, or logs.',
  '- Treat Skill Package updates as full file-tree replacement. If preserving files, read current detail, merge, then submit the complete desired tree.',
  '- Keep changes scoped to the task. Do not rewrite unrelated UI, schema, or API contracts.',
].join('\n');

export const PROJECT_CHANGE_WORKFLOW_CONTENT = [
  '# Project Change Workflow',
  '',
  'Use when changing `lobster-front` or `lobster-back` code.',
  '',
  '## Flow',
  '1. Check git status in the relevant repo because `lobster-front` and `lobster-back` may have separate worktrees.',
  '2. Inspect the target page, controller, DTO/VO, service, mapper, schema, and nearby tests before editing.',
  '3. Add or update focused tests before behavior changes where practical.',
  '4. Keep API payloads aligned between TypeScript services and backend request/response objects.',
  '5. Preserve Skill full-upload and sync preview rules when touching prompts, docs, editor save behavior, or AI API examples.',
  '',
  '## Project Map',
  '| Area | Path | Purpose |',
  '|---|---|---|',
  '| Frontend | `lobster-front` | Vite, React, TypeScript UI for agents, skills, profile, admin, and onboarding docs |',
  '| Backend | `lobster-back` | Spring Boot API, auth, Agent sync, Skill Package storage, audit, and database schema |',
  '| Public manual | `lobster-front/public/docs/ai-agent-api.md` | AI-facing API contract and Agent Token workflow |',
  '| Skill editor | `lobster-front/src/pages/skill/Editor` | Browser editor for Skill Package file trees |',
  '| Skill service | `lobster-back/src/main/java/cn/xcd/lobster/service/impl/SkillServiceImpl.java` | Creates, updates, publishes, forks, and stores Skill files |',
  '| Agent sync service | `lobster-back/src/main/java/cn/xcd/lobster/service/impl/AgentSyncServiceImpl.java` | Agent Token sync, mounted Skill Packages, memories, and goals |',
  '',
  '## When Skill Behavior Changes',
  'Read `references/domain-rules.md` and compare `SkillServiceImpl`, `SkillSaveRequest`, `SkillFileRequest`, `SkillPackageVO`, and `skill_market_seed.sql` together.',
].join('\n');

export const SKILL_PACKAGE_UPLOAD_WORKFLOW_CONTENT = [
  '# Skill Package Upload Workflow',
  '',
  'Use when creating, updating, publishing, forking, or migrating a Skill Package.',
  '',
  '## Required Flow',
  '1. Read current Skill detail first if updating an existing package.',
  '2. Build the complete desired `files` tree. Do not send only changed files.',
  '3. Preserve stable paths with forward slashes: `SKILL.md`, `references/api.md`, `scripts/check.py`.',
  '4. Keep `SKILL.md` concise. Move long API docs, workflows, examples, and troubleshooting into one-level referenced files.',
  '5. Submit create/update only after overwrite risk is clear.',
  '6. Verify the saved Skill detail returns the same file tree.',
  '',
  '## Recommended File Layout',
  '```text',
  'SKILL.md',
  'workflows/<task>.md',
  'references/<topic>.md',
  'examples/<case>.md',
  'scripts/<tool>.*',
  'checklists/<checklist>.md',
  '```',
  '',
  '## Authoring Rules',
  '- `SKILL.md` is the trigger and router, not a data dump.',
  '- Keep references one level deep from `SKILL.md` so agents can find and read complete files.',
  '- Use scripts for deterministic validation or packaging tasks; say whether to run or read each script.',
  '- Avoid Windows-style paths inside Skill files.',
].join('\n');

export const AGENT_SYNC_PREVIEW_WORKFLOW_CONTENT = [
  '# Agent Sync Preview Workflow',
  '',
  'Use before an Agent writes `skills`, `memories`, or `goals` through `/sync`.',
  '',
  '## Required Flow',
  '1. Call `GET /api/ai/agents/{agentId}/config` and read `data.syncRevision`.',
  '2. Compare local desired data with existing `skills`, `memories`, `goals`, `skillMounts`, and `skillPackages`.',
  '3. Produce a 同步预览 showing creates, updates, deletes, skipped items, overwrite risks, target Agent, and categories being written.',
  '4. Ask the user to choose exactly one scope: 全量同步, 只同步 Skill, 只同步记忆, 只同步目标, 只更新 Agent 身份, or cancel.',
  '5. Submit `POST /api/ai/agents/{agentId}/sync` with `baseRevision=data.syncRevision` and `confirmSync=true` when the payload includes `skills`, `memories`, or `goals`.',
  '6. If the backend returns `409`, fetch config again, regenerate the preview, and ask for scope again.',
  '',
  '## Goal Rules',
  '- 目标更新优先复用 config 返回的 `goals[].id`。',
  '- 没有 id 时平台只跳过精确重复目标，不猜测合并。',
  '- 删除过期或重复目标时调用 `DELETE /api/ai/agents/{agentId}/goals/{goalId}`，需要 `goalWrite` 权限。',
  '- 目标在前端按执行任务展示；AI 不需要维护整体百分比。',
  '- 长任务每次同步都复用 config 返回的 `goals[].id`，把阶段进展写入同一目标的 `steps`。',
  '- `steps` 是执行记录：写 `title`、`description`、`status`、`sortOrder`，可选 `updatedAt`；前端只在有步骤时按完成数推导进度。',
  '',
  '## Skill Rules',
  '- `sync.skills` is an Agent self-reported display snapshot, not the Skill Package source of truth.',
  '- If the goal is to create a front-end visible Skill, call `POST /api/ai/skills` instead of only syncing `skills`.',
  '- To auto-mount an existing Skill Package, keep a stable `sync.skills[].configJson.code` matching the package code.',
].join('\n');

export const CONFIG_EVENT_LISTENING_WORKFLOW_CONTENT = [
  '# Config Event Listening Workflow',
  '',
  'Use when an Agent needs to listen for platform-side configuration changes.',
  '',
  '## Polling Loop',
  '1. Periodically call `GET /api/ai/agents/{agentId}/events`.',
  '2. If no pending `config_changed` event exists, continue normal work.',
  '3. For each pending event, call `GET /api/ai/agents/{agentId}/config` before ack.',
  '4. Apply the platform-side changes: identity, mounted Skill Packages, memories, goals, and goal steps.',
  '5. Read mounted Skill Package instructions from `skillPackages[].files`, not only `skills`.',
  '6. After applying the change, call `POST /api/ai/events/{eventId}/ack`.',
  '',
  '## Ack Boundary',
  '- Do not ack before applying config; ack removes the event from future polling.',
  '- Do not wait for or ack the Agent\'s own `/sync` write. Ack is for platform-side or human-side pending `config_changed` events.',
  '- If config pull fails, leave the event pending and retry later.',
].join('\n');

export const RELEASE_VERIFICATION_WORKFLOW_CONTENT = [
  '# Release Verification Workflow',
  '',
  'Use before reporting work as complete or preparing a release.',
  '',
  '## Frontend Commands',
  '| Change Type | Command | Working Directory |',
  '|---|---|---|',
  '| Type check | `npm run lint` | `lobster-front` |',
  '| Production build | `npm run build` | `lobster-front` |',
  '| Targeted tests | `npx tsx --test <test-file>` | `lobster-front` |',
  '',
  '## Backend Commands',
  '| Change Type | Command | Working Directory |',
  '|---|---|---|',
  '| Targeted test | `mvn -Dtest=<TestClass> test` | `lobster-back` |',
  '| Full test suite | `mvn test` | `lobster-back` |',
  '',
  '## Output Contract',
  'When reporting work, include files changed, verification commands run, results, and any command that could not be run.',
].join('\n');

export const DOMAIN_RULES_REFERENCE_CONTENT = [
  '# Domain Rules',
  '',
  '## Source of Truth',
  '- A Skill Package is stored as `skill_package` plus its complete `skill_file` tree.',
  '- `sync.skills` is only an Agent self-reported display snapshot.',
  '- Mounted skills are represented by `agent_skill_mount`.',
  '- Agent config exposes mounted Skill Package files through `skillPackages[].files`.',
  '- Creating or updating a Skill Package requires a complete file tree, not an incremental patch. Treat `files` as the 完整文件树. Missing files from the request will be absent after update.',
  '',
  '## 平台迁移策略',
  '- Codex can usually read workspace files and write the full Skill file tree directly.',
  '- Claude Code may use its own skill-loading and project-instruction conventions.',
  '- 通用 Agent integrations may only support API calls or exported ZIP/JSON backups.',
  '- If a platform can safely read files and config, write a small program or script to build the preview and payload.',
  '- If overwrite risk, missing permissions, or user intent is unclear, stop before sync and ask for selection.',
].join('\n');

export const API_ENDPOINTS_REFERENCE_CONTENT = [
  '# API Endpoints Reference',
  '',
  '## Skill Package',
  '| Purpose | Endpoint | Notes |',
  '|---|---|---|',
  '| Create/update visible Skill Package | `POST /api/ai/skills` | Requires complete files tree |',
  '| Update existing visible Skill Package | `PUT /api/ai/skills/{id}` | Preserve files by reading current detail first |',
  '| Read Skill detail | `GET /api/ai/skills/{id}` | Verify saved files |',
  '',
  '## Agent Config and Sync',
  '| Purpose | Endpoint | Notes |',
  '|---|---|---|',
  '| Read current config | `GET /api/ai/agents/{agentId}/config` | Returns `syncRevision`, `skillPackages[].files`, memories, goals |',
  '| Sync state | `POST /api/ai/agents/{agentId}/sync` | Use `baseRevision` and `confirmSync=true` for skills/memories/goals |',
  '| Poll events | `GET /api/ai/agents/{agentId}/events` | Look for pending `config_changed` |',
  '| Ack event | `POST /api/ai/events/{eventId}/ack` | Ack only after applying config |',
  '| Delete duplicate goal | `DELETE /api/ai/agents/{agentId}/goals/{goalId}` | Requires `goalWrite` |',
  '| Delete duplicate memory | `DELETE /api/ai/agents/{agentId}/memories/{memoryId}` | Requires `memoryWrite` |',
].join('\n');

export const TROUBLESHOOTING_REFERENCE_CONTENT = [
  '# Troubleshooting',
  '',
  '## Skill update lost files',
  'Confirm the request sent a complete `files` array and did not send only changed files.',
  '',
  '## Agent config does not show a Skill',
  'Confirm the Skill Package was uploaded, then mounted manually or auto-mounted by matching `sync.skills[].configJson.code`.',
  '',
  '## Market does not show a Skill',
  'Confirm visibility, publish status, audit status, owner, and delete time.',
  '',
  '## Agent reads only `skills`',
  'Switch to `skillPackages[].files` for complete Skill instructions.',
  '',
  '## Frontend API mismatch',
  'Compare TypeScript service payloads with backend DTOs and VO records.',
  '',
  '## Duplicate goals',
  'Reuse `goals[].id` when updating, and call `DELETE /api/ai/agents/{agentId}/goals/{goalId}` for stale or duplicate goals.',
].join('\n');

export const LOBSTER_WORKFLOW_SCRIPT_CONTENT = [
  '# 知栈 Workflow Checklist',
  '',
  '- Frontend root: lobster-front',
  '- Backend root: lobster-back',
  '- Skill Package source tables: skill_package, skill_file',
  '- Full upload rule: submit the complete files tree on create and update',
  '- Sync preview rule: show planned data and let the user choose 全量同步, 只同步 Skill, 只同步记忆, or 只同步目标 before writing',
  '- Config listening rule: poll events, fetch config, apply changes, then ack',
  '- Goal sync rule: reuse goals[].id for long-running tasks; update steps instead of inventing an overall progress percent; delete stale or duplicate goals with DELETE /api/ai/agents/{agentId}/goals/{goalId}',
  '- 平台迁移策略: adapt Codex, Claude Code, and 通用 Agent workflows to their file-reading and API capabilities',
  '- Frontend checks: npm run lint, npm run build, npx tsx --test <test-file>',
  '- Backend checks: mvn -Dtest=<TestClass> test, mvn test',
].join('\n');

export const DEFAULT_SKILL_FILES: SkillFile[] = [
  {
    name: 'SKILL.md',
    language: 'markdown',
    path: 'SKILL.md',
    content: LOBSTER_WORKFLOW_SKILL_CONTENT,
  },
  {
    name: 'workflows/project-change.md',
    path: 'workflows/project-change.md',
    language: 'markdown',
    content: PROJECT_CHANGE_WORKFLOW_CONTENT,
  },
  {
    name: 'workflows/skill-package-upload.md',
    path: 'workflows/skill-package-upload.md',
    language: 'markdown',
    content: SKILL_PACKAGE_UPLOAD_WORKFLOW_CONTENT,
  },
  {
    name: 'workflows/agent-sync-preview.md',
    path: 'workflows/agent-sync-preview.md',
    language: 'markdown',
    content: AGENT_SYNC_PREVIEW_WORKFLOW_CONTENT,
  },
  {
    name: 'workflows/config-event-listening.md',
    path: 'workflows/config-event-listening.md',
    language: 'markdown',
    content: CONFIG_EVENT_LISTENING_WORKFLOW_CONTENT,
  },
  {
    name: 'workflows/release-verification.md',
    path: 'workflows/release-verification.md',
    language: 'markdown',
    content: RELEASE_VERIFICATION_WORKFLOW_CONTENT,
  },
  {
    name: 'references/domain-rules.md',
    path: 'references/domain-rules.md',
    language: 'markdown',
    content: DOMAIN_RULES_REFERENCE_CONTENT,
  },
  {
    name: 'references/api-endpoints.md',
    path: 'references/api-endpoints.md',
    language: 'markdown',
    content: API_ENDPOINTS_REFERENCE_CONTENT,
  },
  {
    name: 'references/troubleshooting.md',
    path: 'references/troubleshooting.md',
    language: 'markdown',
    content: TROUBLESHOOTING_REFERENCE_CONTENT,
  },
  {
    name: 'checklists/lobster-checklist.md',
    path: 'checklists/lobster-checklist.md',
    language: 'markdown',
    content: LOBSTER_WORKFLOW_SCRIPT_CONTENT,
  },
];

export const cloneDefaultSkillFiles = () => DEFAULT_SKILL_FILES.map((file) => ({ ...file }));
const yamlSafeLine = (value: string) => value.replace(/\r?\n/g, ' ').trim();

export function buildSkillStarterFiles(name: string, description = ''): SkillFile[] {
  const skillName = yamlSafeLine(name) || '未命名技能';
  const skillDescription = yamlSafeLine(description) || '请补充该 Skill 的能力边界、输入输出和调用方式。';

  return [
    {
      name: 'SKILL.md',
      path: 'SKILL.md',
      language: 'markdown',
      content: [
        '---',
        `name: ${skillName}`,
        `description: Use when ${skillDescription}`,
        '---',
        '',
        `# ${skillName}`,
        '',
        skillDescription,
        '',
        '## 使用方式',
        '1. 先读 `workflows/usage.md` 判断是否适合当前任务。',
        '2. 需要入参、输出或边界时读 `references/interface.md`。',
        '3. 需要请求或调用样例时读 `examples/request.md`。',
        '4. 完成前按 `checklists/quality.md` 验证。',
        '',
        '## 安全边界',
        '- 不写入密钥、Token、用户隐私或生产凭据。',
        '- 不执行未说明的破坏性操作。',
        '- 当前 Skill 信息不足时先停下并要求补充。',
      ].join('\n'),
    },
    {
      name: 'workflows/usage.md',
      path: 'workflows/usage.md',
      language: 'markdown',
      content: [
        `# ${skillName} Usage Workflow`,
        '',
        '## 触发条件',
        `使用该 Skill 处理：${skillDescription}`,
        '',
        '## 执行流程',
        '1. 明确用户目标、输入数据和成功标准。',
        '2. 检查 `references/interface.md` 中的输入、输出和限制。',
        '3. 按最小必要步骤执行任务。',
        '4. 记录产生的结果、失败原因或需要用户确认的风险。',
        '5. 按 `checklists/quality.md` 做最终验证。',
        '',
        '## 需要暂停的情况',
        '- 缺少必要输入。',
        '- 操作可能覆盖、删除或泄露数据。',
        '- 当前任务超出该 Skill 的能力边界。',
      ].join('\n'),
    },
    {
      name: 'references/interface.md',
      path: 'references/interface.md',
      language: 'markdown',
      content: [
        `# ${skillName} Interface`,
        '',
        '## 输入',
        '- 用户目标：必填。',
        '- 上下文或数据源：按任务提供。',
        '- 约束条件：权限、时间、范围、安全要求。',
        '',
        '## 输出',
        '- 处理结果。',
        '- 关键决策或假设。',
        '- 未完成事项和阻塞原因。',
        '',
        '## 能力边界',
        '- 在这里写清楚该 Skill 可以做什么。',
        '- 在这里写清楚该 Skill 不能做什么。',
      ].join('\n'),
    },
    {
      name: 'examples/request.md',
      path: 'examples/request.md',
      language: 'markdown',
      content: [
        `# ${skillName} Examples`,
        '',
        '## 示例请求',
        '```text',
        `请使用 ${skillName} 处理：[替换为具体任务]`,
        '输入：[替换为数据或上下文]',
        '要求：[替换为输出格式或限制]',
        '```',
        '',
        '## 示例输出',
        '```text',
        '结果：[说明处理结果]',
        '验证：[说明如何确认结果有效]',
        '```',
      ].join('\n'),
    },
    {
      name: 'checklists/quality.md',
      path: 'checklists/quality.md',
      language: 'markdown',
      content: [
        `# ${skillName} Quality Checklist`,
        '',
        '- [ ] 已确认任务属于该 Skill 的触发条件。',
        '- [ ] 已检查输入是否完整。',
        '- [ ] 已遵守安全边界。',
        '- [ ] 已说明关键假设。',
        '- [ ] 已完成必要验证。',
        '- [ ] 已报告无法完成的部分。',
      ].join('\n'),
    },
  ];
}
